language: node_js

node_js:
  - 6.10

script:
  - node node_modules/jasmine/bin/jasmine.js

notifications:
  email:
    recipients:
      - alanmatkorsky@gmail.com
      - leandro.jdl@gmail.com
    on_success: change
    on_failure: change
